### PR TITLE
Align variable initialization

### PR DESCRIPTION
**Pull request by aravindavk**
These settings aligns variables as below.

    int              ret            = -1;
    quota_meta_t    *meta_dst       = NULL;
    quota_meta_t    *meta_src       = NULL;
    int64_t         *size           = NULL;
    int64_t          dst_dir_count  = 0;
    int64_t          src_dir_count  = 0;

Ref: http://releases.llvm.org/5.0.0/tools/clang/docs/ClangFormatStyleOptions.html

Signed-off-by: Aravinda VK <mail@aravindavk.in>

### CODE REVIEW

**Comment by nigelbabu** [comment]
Note: This actually does 

    xlator_t *    dst_node,

**Comment by aravindavk** [comment]
> xlator_t *    dst_node,

Thats bad, `AlignConsecutiveDeclarations: true` is not understanding the variables in function definitions. I will get back on this part.

**Comment by aravindavk** [comment]
Looks like there is a issue with `clang-format` https://stackoverflow.com/questions/38392889/clang-format-align-asterisk-of-pointer-declaration-with-variable-name

**Comment by nigelbabu** [comment]
Looks like it's not implemented in master either, so we may want to turn this off to whatever is the default value.

**Pull request merged**
